// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package apiserver

import (
	"github.com/pachirode/go_blog_study/internal/apiserver/biz"
	"github.com/pachirode/go_blog_study/internal/apiserver/pkg/validation"
	"github.com/pachirode/go_blog_study/internal/apiserver/store"
	"github.com/pachirode/go_blog_study/internal/pkg/server"
	"github.com/pachirode/pkg/authz"
)

// Injectors from wire.go:

func InitializeWebServer(config *Config) (server.Server, error) {
	string2 := config.ServerMode
	db, err := ProvideDB(config)
	if err != nil {
		return nil, err
	}
	dataStore := store.NewStore(db)
	v := authz.DefaultOptions()
	authzAuthz, err := authz.NewAuthz(db, v...)
	if err != nil {
		return nil, err
	}
	bizBiz := biz.NewBiz(dataStore, authzAuthz)
	validator := validation.New(dataStore)
	userRetriever := &UserRetriever{
		store: dataStore,
	}
	serverConfig := &ServerConfig{
		cfg:       config,
		biz:       bizBiz,
		val:       validator,
		retriever: userRetriever,
		authz:     authzAuthz,
	}
	serverServer, err := NewWebServer(string2, serverConfig)
	if err != nil {
		return nil, err
	}
	return serverServer, nil
}
