server-mode: gin
# JWT 签发密钥
jwt-key: ed94598741cdda4b9bd378c13a58fd31
# JWT Token 过期时间
jwt-expire: 12h
# 是否启用内存数据库
enable-memory-db: true

# 服务器安全相关
tls:
  use-tls: false
  cert: ./_output/cert/server.crt
  key: ./_output/cert/server.key

http:
  addr: :5555

grpc:
  addr: :6666

mysql:
  addr: 127.0.0.1
  username: miniblog
  password: miniblog1234
  database: miniblog
  max-idle-connections: 100
  max-open-connections: 100
  max-connection-life-time: 100
  log-level: 4

log:
  disable-caller: false
  disable-stacktrace: false
  level: debug
  format: console
  output-paths: [ ./miniblog.log, stdout ]
