db:
  host: 127.0.0.1
  username: miniblog
  password: miniblog1234
  database: miniblog
  max-idle-connections: 100
  max-open-connections: 100
  max-connection-life-time: 100
  log-level: 4
log:
  disable-caller: false
  disable-stacktrace: false
  level: debug
  format: console
  output-paths: [/tmp/miniblog.log, stdout]
web:
  runmode: debug
  addr: 0.0.0.0:8080
