db:
  host: 127.0.0.1
  username: miniblog
  password: miniblog1234
  database: miniblog
  log-level: 4
log:
  disable-caller: false
  disable-stacktrace: false
  level: debug
  format: console
  output-paths: [/tmp/miniblog.log, stdout]
